### ISSUE TITLE
BUG:查询返回文件夹下无此图片

### ISSUE THREAD

**Issue by PAKingdom** [limbang/mirai-console-mcmod-plugin#15]
复现步骤
百科资料 草方块
0

https://www.toptal.com/developers/hastebin/anopinunuk.lua

日志↑

百科模组 ic2
13

https://www.toptal.com/developers/hastebin/ofoxisefic.lua

日志↑

使用您的插件mirai-console-jcf-plugin-无此问题

**Comment by PAKingdom** [comment]
我知道这应该是我的问题，但是我不知道出在哪里

**Comment by jie65535** [comment]
有没有一种可能，你的硬盘已经满了。

**Comment by PAKingdom** [comment]
> 有没有一种可能，你的硬盘已经满了。

不，请审题 
使用jcf无此问题

**Comment by jie65535** [comment]
我大概知道是什么问题了，应该是高版本`mirai`数据目录迁移的问题。
你使用的是什么版本的`mirai`？

**Comment by PAKingdom** [comment]
2.9.0-rc2

**Comment by jie65535** [comment]
我编译了一个修复版本，请你测试验证是否有效。

[mirai-console-mcmod-plugin-1.2.0.mirai.jar.zip](https://github.com/limbang/mirai-console-mcmod-plugin/files/7874393/mirai-console-mcmod-plugin-1.2.0.mirai.jar.zip)

**Comment by PAKingdom** [comment]
> 我编译了一个修复版本，请您测试验证是否有效。
> 
> [mirai-console-mcmod-plugin-1.2.0.mirai.jar.zip](https://github.com/limbang/mirai-console-mcmod-plugin/files/7874393/mirai-console-mcmod-plugin-1.2.0.mirai.jar.zip)

有效√
