### ISSUE TITLE
疑似mcmodUA检测更新

### ISSUE THREAD

**Issue by 502milk** [limbang/mirai-console-mcmod-plugin#17]
访问mcmod返回
`<!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" /><title>跳转中...</title></head><body><div id="svg-circles"></div><div class="l-wrapper"><script>window['yjs_js_challenge_token']='d7cefe883e70cf51cb02d2999e9c5245a0584b6f_1643100774'</script><script type="text/javascript" src="/.well-known/yunjiasu-cgi/scripts/miao.v2.min.js"></script><script type="text/javascript" src="/.well-known/yunjiasu-cgi/scripts/jschl.js"></script></div></body></html>`
并导致报错

复现步骤：只要涉及到内容部分，即会返回上文

**Comment by limbang** [comment]
有具体复现方式么

**Comment by 502milk** [comment]
已找到问题，那段时间mcmod图库被打了，导致部分流量异常
