### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by 502milk** [limbang/mirai-console-mcmod-plugin#2]
希望可以添加自定义命令搜索
例如百科模组 IC2 通过自定义改为/mod IC2
添加mcmod的原链接及相关链接功能
最好在合并转发内，有点刷屏

**Comment by limbang** [comment]
识别命令可以弄成自定义，但是带/就涉及到权限问题了
具体原链接是指什么，能否发个模版

**Comment by limbang** [comment]
如果用合并转发感觉还是有点奇怪，考虑是否做个翻页
<img width="276" alt="9FE1841E-5307-40D2-892B-875B41A06BB1" src="https://user-images.githubusercontent.com/6381512/124608017-f4e95c80-dea0-11eb-88c0-31999846487b.png">
![9F78763F-66F8-4B8E-AFBA-267A1B4ACCF2](https://user-images.githubusercontent.com/6381512/124608031-f74bb680-dea0-11eb-8785-a7d5dc2635db.png)
![671C9C57-697D-4617-846F-D9A46BFE02AA](https://user-images.githubusercontent.com/6381512/124608048-fadf3d80-dea0-11eb-9e67-ff20a467cdad.png)

**Comment by 502milk** [comment]
> 识别命令可以弄成自定义，但是带/就涉及到权限问题了
> 具体原链接是指什么，能否发个模版
 emmmmmmm，之前重生好像是给了一个人mcmod的api，然后他写了一个机器人，其中命令就是/ss的，返回内容是mcmod的链接
我再1.0.2版本插件上强行把命令改成了/开头的命令，似乎并没有遇到mirai的权限问题
（不然合并转发和翻页二选一吧）
（mirai版本2.7-M1，已安装插件chat-command-0.5.1，MiraiSongPlugin-2.7-1.0.5，Plum，mirai-console-mcmod-plugin-1.0.1）

**Comment by 502milk** [comment]
> 识别命令可以弄成自定义，但是带/就涉及到权限问题了
> 具体原链接是指什么，能否发个模版

恩，再强行把命令改成/开头的指令似乎并没有遇到权限问题
普通成员及管理员均能触发命令
用的最新1.0.3版本代码
（我不知道为啥我每次编译都没有库（捂脸，我tcl

**Comment by limbang** [comment]
![B79B4ECB-FF8E-4D29-B62E-B770A47A017B](https://user-images.githubusercontent.com/6381512/124779189-25e69180-df74-11eb-848b-52dff5150440.png)
编译的时候用这个编译，或者 shadow 里面那个也行
