### ISSUE TITLE
Bug: 无法按“整合包”分类搜索

### ISSUE THREAD

**Issue by sxjeru** [limbang/mirai-console-mcmod-plugin#22]
使用`整合包`分类（modpack）搜索时，只能得到`模组`分类（class）的结果，且不完整。

**Comment by limbang** [comment]
![image](https://user-images.githubusercontent.com/6381512/154406314-3732d588-3244-4775-82d7-7e4fb5433bf9.png)
 我好像是正常的

**Comment by sxjeru** [comment]
未知问题，版本为 1.2.1

![image](https://user-images.githubusercontent.com/20513115/154413583-f9685bc1-a510-4bd5-aaf1-cfdd72c58efd.png)
![image](https://user-images.githubusercontent.com/20513115/154413635-47e30f0e-ae43-4b0b-a580-39bad69a6dd3.png)

**Comment by limbang** [comment]
![image](https://user-images.githubusercontent.com/6381512/154444441-aac1bc0b-5904-4f3a-a1ae-6c598545d9a3.png)
![image](https://user-images.githubusercontent.com/6381512/154444570-81c0a978-640e-43ae-ac94-e15330a7da25.png)

**Comment by limbang** [comment]
![image](https://user-images.githubusercontent.com/6381512/154444713-11d63a9f-22f2-410e-96cb-a797c4cabb3d.png)
把版本更新试试？

**Comment by sxjeru** [comment]
~~更新到 v1.2.2 了，还是一样的问题。~~

知道问题了，由于命令与搜索关键词之间不需要空格隔开，导致“/modpack”成了搜索带“pack”的mod了。

抱歉打扰了。
