### ISSUE TITLE
无法关闭戳一戳菜单

### ISSUE THREAD

**Issue by floudfox** [limbang/mirai-console-mcmod-plugin#23]

**Comment by jie65535** [comment]
`/mcmod setNudgeEnabled false`
命令执行后需要重载插件生效。

**Comment by floudfox** [comment]
命令执行后，重启，搓一搓后依然显示菜单






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月15日(星期二) 上午10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [limbang/mirai-console-mcmod-plugin] 无法关闭戳一戳菜单 (Issue #23)





 
/mcmod setNudgeEnabled false
 命令执行后需要重载插件生效。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jie65535** [comment]
检查`./data/top.limbang.mirai-console-mcmod-plug/mcmod.yml`文件内容

**Comment by floudfox** [comment]
谢谢，已解决
