### ISSUE TITLE
建议可选保留百科站链接

### ISSUE THREAD

**Issue by sxjeru** [limbang/mirai-console-mcmod-plugin#27]
用 v2 版本后发现如果结果能全部显示，则开头的百科站链接会被省略。
实际上转发消息中的资料可能存在排版缺失等问题，因此希望能给予配置选项，始终显示百科站链接。

`感谢代码贡献，辛苦了！`

**Comment by limbang** [comment]
意思是显示原始页面的 url ？

**Comment by sxjeru** [comment]
是的。譬如搜索IC2并输入序号后，转发消息第一条为logo，第二条可以为“[https://www.mcmod.cn/class/2.html](https://www.mcmod.cn/class/2.html)”。
