### ISSUE TITLE
建议保留搜索列表

### ISSUE THREAD

**Issue by 502milk** [limbang/mirai-console-mcmod-plugin#28]
保留搜索列表内容，直到下一次搜索或N分钟后

例:
比如我搜索了IC2
返回了IC2及IC2附属等mod
选择一个序号查看后可以继续选择别的序号查看

**Comment by limbang** [comment]
建议重新搜索，现在设计是可以支持多人同时搜索的，如果按你说的保留列表，要么都保存一个列表，直到下次搜索替换，但是这会导致多人冲突，要么就把每个人的数据都存着，占用太多资源

**Comment by limbang** [comment]
也可以考虑这样逻辑，只要合规输入就挂起等待下一次输入，如果不合规就输出错误消息，并结束挂起，但是这样也是导致一个问题，不需要二次查询的人，在正确查询后随便输入什么都会得到一条错误的消息，看看你有啥见解吧

**Comment by 502milk** [comment]
那就用超时设计吧，在一起合规输入后1分钟内无任何合规输入则撤回列表结束搜索，若输入其他不合规内容无回复

**Comment by limbang** [comment]
如果启用副作用 1. 每次都会撤回列表在发送（不如不想这样需要改动的地方太多了，暂时不考虑实现）2.最后都会显示“等待超时,请重新查询”（这个也不好改 改了会有一个空消息的报错要处理，也不考虑实现）
