### ISSUE TITLE
建议命令精准匹配

### ISSUE THREAD

**Issue by 502milk** [limbang/mirai-console-mcmod-plugin#30]
避免某些情况下的误触
(比如搜mod的命令是mod)
然后打了一句话是mod开头导致被触发
~~啊。。被触发好多次的绝望~~

**Comment by limbang** [comment]
其实设置自定义命令的时候自己加个空格也可以

**Comment by jie65535** [comment]
不行的，默认指令系统后面的空格会丢掉。而且它也不支持`"mod "`这种参数。
