### ISSUE TITLE
显示模组相关链接内容为空

### ISSUE THREAD

**Issue by 502milk** [limbang/mirai-console-mcmod-plugin#35]
在启用这个功能后仅返回“相关链接:”
![image](https://user-images.githubusercontent.com/49502047/215722136-d8acbe49-712d-4f90-ba54-42afc74dad60.png)
如图

**Comment by 502milk** [comment]
![@S3M9O2V9Q(8~8W3}KBY6BT](https://user-images.githubusercontent.com/49502047/218471610-a8cedafa-6ade-4ffd-9571-7961dc2a1ecb.png)
后补链接改为防盗链
https://link.mcmod.cn/target/aHR0cHM6Ly93d3cuY3Vyc2Vmb3JnZS5jb20vbWluZWNyYWZ0L21jLW1vZHMvdHJlZS1oYXJ2ZXN0ZXI=
“https://link.mcmod.cn/target/”之后为base64编码URL，解密即为原链接

**Comment by limbang** [comment]
好的。有空更新
