### ISSUE TITLE
机器人回复的图片不生效

### ISSUE THREAD

**Issue by NeverMine0** [limbang/mirai-console-mcmod-plugin#38]
如下图
查询物品的图片生效，MCmod中简介栏图片不生效
但是效仿readme中查询教程功能与查询整合包功能
机器人回复的内容中图片不生效
请问该如何解决

![QQ图片20240305144136](https://github.com/limbang/mirai-console-mcmod-plugin/assets/162126030/4e22b6de-415b-43ae-bb16-c3823ab0ec15)

![QQ截图20240305143756](https://github.com/limbang/mirai-console-mcmod-plugin/assets/162126030/f86da9c1-a609-45b8-b29e-f485237eeb4d)

**Comment by jie65535** [comment]
这主要是因为这些图片以webp格式显示，而Mirai只支持git/png/bmp/jpg，所以无法正常显示。
![image](https://github.com/limbang/mirai-console-mcmod-plugin/assets/29452349/ed01250a-8719-4748-ad18-d9b7d7817bc1)

如果要显示WebP图片，需要将其转为PNG进行发送，参考 https://github.com/mamoe/mirai/issues/1584

**Comment by limbang** [comment]
更新到 [v2.1.0](https://github.com/limbang/mirai-console-mcmod-plugin/releases/tag/v2.1.0) 版本
