### ISSUE TITLE
由于QQ更改了转发消息，编号不显示

### ISSUE THREAD

**Issue by XC084** [limbang/mirai-console-mcmod-plugin#39]
![Screenshot_2024-03-24-06-39-13-725_com tencent mobileqq-edit](https://github.com/limbang/mirai-console-mcmod-plugin/assets/99209606/6ca30333-8d64-40af-acce-920665afd31c)
![Screenshot_2024-03-24-06-39-30-186_com tencent mobileqq-edit](https://github.com/limbang/mirai-console-mcmod-plugin/assets/99209606/e02b5d4f-2ed4-47c6-8c72-2aea1402965d)
如图所示，因为腾讯转发消息不再能改发送人名字。
所以回复编号查看，要数一下，没办法第一时间获取编号信息。
可以改成在发出的搜索结果前加编号
(不改也不影响使用(

**Comment by limbang** [comment]
<img width="600" alt="image" src="https://github.com/limbang/mirai-console-mcmod-plugin/assets/6381512/c95eacdb-d1e7-4872-9a3b-5b0a9f07605b">
奇怪我这是正常的。那更新下把
